{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rancher-fleet-secrets-annotater.fullname" . }}
  labels:
{{ include "rancher-fleet-secrets-annotater.labels" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups: ["fleet.cattle.io"]
    resources: ["clusters"]
    verbs:
      - get
      - list
      - watch
      - update
      - patch
{{- end -}}
